# Generated by Django 3.1.7 on 2021-03-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210319_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='page_id',
        ),
    ]
