# Generated by Django 3.1.7 on 2021-03-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20210319_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
