# Generated by Django 3.1.7 on 2021-03-24 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_post_readed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='page_id',
            new_name='page',
        ),
    ]
